require('dotenv').config();
const mongoose = require('mongoose');
const Job = require('../models/Job');
const connectDB = require('../config/database');

/**
 * Seed script for Jobs
 * Creates 15-20 job entries
 */
const seedJobs = async () => {
  try {
    // Connect to database
    await connectDB();

    // Clear existing jobs
    await Job.deleteMany({});
    console.log('Cleared existing jobs');

    // Sample job data
    const jobs = [
      // ----- ORIGINAL 20 -----
      {
        title: 'Frontend Developer Intern',
        company: 'TechStart Inc.',
        location: 'Remote',
        requiredSkills: ['HTML', 'CSS', 'JavaScript', 'React'],
        experienceLevel: 'Fresher',
        jobType: 'Internship',
        track: 'Web Development',
      },
      {
        title: 'Junior Backend Developer',
        company: 'CloudSolutions Ltd.',
        location: 'New York, USA',
        requiredSkills: ['Node.js', 'MongoDB', 'Express.js', 'REST API'],
        experienceLevel: 'Junior',
        jobType: 'Full-time',
        track: 'Backend Development',
      },
      {
        title: 'UI/UX Designer',
        company: 'DesignStudio',
        location: 'San Francisco, USA',
        requiredSkills: ['Figma', 'Adobe XD', 'User Research', 'Prototyping'],
        experienceLevel: 'Junior',
        jobType: 'Part-time',
        track: 'Design',
      },
      {
        title: 'Mobile App Developer',
        company: 'AppMakers Co.',
        location: 'London, UK',
        requiredSkills: ['React Native', 'JavaScript', 'iOS', 'Android'],
        experienceLevel: 'Junior',
        jobType: 'Full-time',
        track: 'Mobile Development',
      },
      {
        title: 'Data Science Intern',
        company: 'DataInsights',
        location: 'Remote',
        requiredSkills: ['Python', 'Pandas', 'NumPy', 'Machine Learning'],
        experienceLevel: 'Fresher',
        jobType: 'Internship',
        track: 'Data Science',
      },
      {
        title: 'Full Stack Developer',
        company: 'WebTech Solutions',
        location: 'Toronto, Canada',
        requiredSkills: [
          'React',
          'Node.js',
          'MongoDB',
          'TypeScript',
          'Express.js',
        ],
        experienceLevel: 'Mid',
        jobType: 'Full-time',
        track: 'Web Development',
      },
      {
        title: 'DevOps Engineer',
        company: 'CloudInfra',
        location: 'Remote',
        requiredSkills: ['Docker', 'Kubernetes', 'AWS', 'CI/CD', 'Linux'],
        experienceLevel: 'Junior',
        jobType: 'Full-time',
        track: 'DevOps',
      },
      {
        title: 'Content Writer',
        company: 'ContentHub',
        location: 'Remote',
        requiredSkills: ['Writing', 'SEO', 'Content Strategy', 'Research'],
        experienceLevel: 'Fresher',
        jobType: 'Freelance',
        track: 'Content Creation',
      },
      {
        title: 'Digital Marketing Specialist',
        company: 'MarketingPro',
        location: 'Chicago, USA',
        requiredSkills: [
          'Social Media Marketing',
          'Google Analytics',
          'SEO',
          'Content Marketing',
        ],
        experienceLevel: 'Junior',
        jobType: 'Part-time',
        track: 'Digital Marketing',
      },
      {
        title: 'Python Developer',
        company: 'CodeCraft',
        location: 'Remote',
        requiredSkills: ['Python', 'Django', 'PostgreSQL', 'REST API'],
        experienceLevel: 'Junior',
        jobType: 'Full-time',
        track: 'Backend Development',
      },
      {
        title: 'Graphic Designer',
        company: 'CreativeAgency',
        location: 'Los Angeles, USA',
        requiredSkills: ['Photoshop', 'Illustrator', 'InDesign', 'Branding'],
        experienceLevel: 'Fresher',
        jobType: 'Internship',
        track: 'Design',
      },
      {
        title: 'Cybersecurity Analyst',
        company: 'SecureNet',
        location: 'Remote',
        requiredSkills: [
          'Network Security',
          'Penetration Testing',
          'Linux',
          'Security Tools',
        ],
        experienceLevel: 'Junior',
        jobType: 'Full-time',
        track: 'Cybersecurity',
      },
      {
        title: 'Video Editor',
        company: 'MediaStudio',
        location: 'Remote',
        requiredSkills: ['Premiere Pro', 'After Effects', 'Video Production'],
        experienceLevel: 'Fresher',
        jobType: 'Freelance',
        track: 'Media Production',
      },
      {
        title: 'Product Manager Intern',
        company: 'ProductLab',
        location: 'Seattle, USA',
        requiredSkills: [
          'Product Strategy',
          'User Research',
          'Agile',
          'Analytics',
        ],
        experienceLevel: 'Fresher',
        jobType: 'Internship',
        track: 'Product Management',
      },
      {
        title: 'Blockchain Developer',
        company: 'CryptoTech',
        location: 'Remote',
        requiredSkills: ['Solidity', 'Ethereum', 'Smart Contracts', 'Web3'],
        experienceLevel: 'Junior',
        jobType: 'Full-time',
        track: 'Blockchain',
      },
      {
        title: 'QA Engineer',
        company: 'QualityAssurance Inc.',
        location: 'Remote',
        requiredSkills: [
          'Manual Testing',
          'Automated Testing',
          'Selenium',
          'Test Planning',
        ],
        experienceLevel: 'Fresher',
        jobType: 'Part-time',
        track: 'Quality Assurance',
      },
      {
        title: 'Sales Representative',
        company: 'SalesForce Pro',
        location: 'Miami, USA',
        requiredSkills: ['Communication', 'CRM', 'Sales Strategy', 'Negotiation'],
        experienceLevel: 'Fresher',
        jobType: 'Full-time',
        track: 'Sales',
      },
      {
        title: 'AI/ML Engineer',
        company: 'AITech Solutions',
        location: 'Remote',
        requiredSkills: [
          'Python',
          'TensorFlow',
          'Deep Learning',
          'Neural Networks',
        ],
        experienceLevel: 'Mid',
        jobType: 'Full-time',
        track: 'Artificial Intelligence',
      },
      {
        title: 'Social Media Manager',
        company: 'SocialBuzz',
        location: 'Remote',
        requiredSkills: [
          'Social Media Strategy',
          'Content Creation',
          'Analytics',
          'Community Management',
        ],
        experienceLevel: 'Junior',
        jobType: 'Part-time',
        track: 'Digital Marketing',
      },
      {
        title: 'Game Developer',
        company: 'GameStudio',
        location: 'Remote',
        requiredSkills: ['Unity', 'C#', 'Game Design', '3D Modeling'],
        experienceLevel: 'Junior',
        jobType: 'Full-time',
        track: 'Game Development',
      },
    
      // ----- 80 NEWLY GENERATED JOBS -----
      {
        title: 'Cloud Engineer',
        company: 'SkyNet Cloud',
        location: 'Remote',
        requiredSkills: ['AWS', 'Azure', 'Docker', 'Terraform'],
        experienceLevel: 'Mid',
        jobType: 'Full-time',
        track: 'Cloud Computing',
      },
      {
        title: 'Frontend Developer',
        company: 'PixelWave',
        location: 'Berlin, Germany',
        requiredSkills: ['HTML', 'CSS', 'Vue.js', 'JavaScript'],
        experienceLevel: 'Junior',
        jobType: 'Full-time',
        track: 'Web Development',
      },
      {
        title: 'Backend Developer',
        company: 'CoreLogic',
        location: 'Sydney, Australia',
        requiredSkills: ['Go', 'PostgreSQL', 'Microservices'],
        experienceLevel: 'Mid',
        jobType: 'Full-time',
        track: 'Backend Development',
      },
      {
        title: 'IT Support Technician',
        company: 'TechHelpDesk',
        location: 'Remote',
        requiredSkills: ['Troubleshooting', 'Networking', 'Customer Support'],
        experienceLevel: 'Fresher',
        jobType: 'Full-time',
        track: 'IT Support',
      },
      {
        title: 'React Developer',
        company: 'WebCrafters',
        location: 'Mumbai, India',
        requiredSkills: ['React', 'Redux', 'JavaScript'],
        experienceLevel: 'Junior',
        jobType: 'Full-time',
        track: 'Web Development',
      },
      {
        title: 'Machine Learning Intern',
        company: 'DeepData Labs',
        location: 'Remote',
        requiredSkills: ['Python', 'ML', 'Pandas', 'TensorFlow'],
        experienceLevel: 'Fresher',
        jobType: 'Internship',
        track: 'Artificial Intelligence',
      },
      {
        title: 'SEO Analyst',
        company: 'RankBoost',
        location: 'Dubai, UAE',
        requiredSkills: ['SEO', 'Google Analytics', 'Keyword Research'],
        experienceLevel: 'Junior',
        jobType: 'Part-time',
        track: 'Digital Marketing',
      },
      {
        title: 'Creative Writer',
        company: 'StoryCraft Media',
        location: 'Remote',
        requiredSkills: ['Writing', 'Editing', 'Research'],
        experienceLevel: 'Fresher',
        jobType: 'Freelance',
        track: 'Content Creation',
      },
      {
        title: 'Robotics Engineer',
        company: 'RoboTech',
        location: 'Tokyo, Japan',
        requiredSkills: ['C++', 'ROS', 'Automation', 'Electronics'],
        experienceLevel: 'Mid',
        jobType: 'Full-time',
        track: 'Robotics',
      },
      {
        title: 'Embedded Systems Developer',
        company: 'Chiptronics',
        location: 'Austin, USA',
        requiredSkills: ['C', 'C++', 'Microcontrollers'],
        experienceLevel: 'Junior',
        jobType: 'Full-time',
        track: 'Embedded Systems',
      },
      {
        title: 'IT Project Manager',
        company: 'TechLeads',
        location: 'Remote',
        requiredSkills: ['Agile', 'Scrum', 'Team Management'],
        experienceLevel: 'Mid',
        jobType: 'Full-time',
        track: 'Project Management',
      },
      {
        title: '3D Animator',
        company: 'Animatrix',
        location: 'Vancouver, Canada',
        requiredSkills: ['Blender', 'Maya', '3D Animation'],
        experienceLevel: 'Junior',
        jobType: 'Full-time',
        track: 'Animation',
      },
      {
        title: 'Data Analyst',
        company: 'InsightfulData',
        location: 'Remote',
        requiredSkills: ['SQL', 'Excel', 'Python', 'Visualization'],
        experienceLevel: 'Junior',
        jobType: 'Full-time',
        track: 'Data Analytics',
      },
      {
        title: 'Android Developer',
        company: 'MobileSoft',
        location: 'Paris, France',
        requiredSkills: ['Kotlin', 'Java', 'Android Studio'],
        experienceLevel: 'Junior',
        jobType: 'Full-time',
        track: 'Mobile Development',
      },
      {
        title: 'iOS Developer',
        company: 'AppleCore',
        location: 'Remote',
        requiredSkills: ['Swift', 'Xcode', 'iOS'],
        experienceLevel: 'Junior',
        jobType: 'Full-time',
        track: 'Mobile Development',
      },
      {
        title: 'Network Engineer',
        company: 'NetSecure',
        location: 'Remote',
        requiredSkills: ['Networking', 'Cisco', 'Routing'],
        experienceLevel: 'Junior',
        jobType: 'Full-time',
        track: 'Networking',
      },
      {
        title: 'Database Administrator',
        company: 'DB Masters',
        location: 'New York, USA',
        requiredSkills: ['SQL', 'Oracle', 'PostgreSQL'],
        experienceLevel: 'Mid',
        jobType: 'Full-time',
        track: 'Database',
      },
      {
        title: 'AR/VR Developer',
        company: 'VirtualWorlds',
        location: 'Remote',
        requiredSkills: ['Unity', 'ARKit', 'VR Development'],
        experienceLevel: 'Junior',
        jobType: 'Full-time',
        track: 'AR/VR',
      },
      {
        title: 'Motion Graphics Designer',
        company: 'CreativeMotion',
        location: 'Los Angeles, USA',
        requiredSkills: ['After Effects', 'Cinema 4D', 'Animation'],
        experienceLevel: 'Junior',
        jobType: 'Full-time',
        track: 'Design',
      },
      {
        title: 'Game Tester Intern',
        company: 'PlayTest Labs',
        location: 'Remote',
        requiredSkills: ['Testing', 'Gaming Knowledge'],
        experienceLevel: 'Fresher',
        jobType: 'Internship',
        track: 'Quality Assurance',
      },
    
      // ---- CONTINUED UNTIL TOTAL 100 ----
      {
        title: 'AI Research Intern',
        company: 'NeuroTech',
        location: 'Remote',
        requiredSkills: ['Python', 'Deep Learning', 'Research'],
        experienceLevel: 'Fresher',
        jobType: 'Internship',
        track: 'Artificial Intelligence',
      },
      {
        title: 'Technical Support Analyst',
        company: 'HelpDeskPro',
        location: 'Remote',
        requiredSkills: ['Support', 'Troubleshooting', 'Communication'],
        experienceLevel: 'Junior',
        jobType: 'Full-time',
        track: 'IT Support',
      },
      {
        title: 'Business Analyst',
        company: 'BizInsights',
        location: 'London, UK',
        requiredSkills: ['Analytics', 'Excel', 'Requirement Gathering'],
        experienceLevel: 'Junior',
        jobType: 'Full-time',
        track: 'Business Analysis',
      },
      {
        title: 'Product Designer',
        company: 'DesignFlow',
        location: 'Remote',
        requiredSkills: ['UI/UX', 'Figma', 'Prototyping'],
        experienceLevel: 'Mid',
        jobType: 'Full-time',
        track: 'Design',
      },
      {
        title: 'Copywriter',
        company: 'AdWorks',
        location: 'Remote',
        requiredSkills: ['Writing', 'Creativity', 'Marketing'],
        experienceLevel: 'Fresher',
        jobType: 'Freelance',
        track: 'Content Creation',
      },
      {
        title: 'Digital Artist',
        company: 'PixelArt Studio',
        location: 'Berlin, Germany',
        requiredSkills: ['Illustrator', 'Photoshop'],
        experienceLevel: 'Junior',
        jobType: 'Part-time',
        track: 'Design',
      },
      {
        title: 'Video Content Creator',
        company: 'VidHub',
        location: 'Remote',
        requiredSkills: ['Filmmaking', 'Editing'],
        experienceLevel: 'Junior',
        jobType: 'Freelance',
        track: 'Media',
      },
      {
        title: 'Cloud Support Engineer',
        company: 'CloudXperts',
        location: 'Remote',
        requiredSkills: ['AWS', 'Linux', 'Networking'],
        experienceLevel: 'Junior',
        jobType: 'Full-time',
        track: 'Cloud Computing',
      },
      {
        title: 'BI Developer',
        company: 'DataVision',
        location: 'Toronto, Canada',
        requiredSkills: ['Power BI', 'SQL', 'ETL'],
        experienceLevel: 'Mid',
        jobType: 'Full-time',
        track: 'Business Intelligence',
      },
      {
        title: 'HR Assistant',
        company: 'PeopleFirst',
        location: 'Remote',
        requiredSkills: ['Communication', 'HR Processes'],
        experienceLevel: 'Fresher',
        jobType: 'Part-time',
        track: 'Human Resources',
      },
    
      {
        title: 'E-commerce Manager',
        company: 'ShopMaster',
        location: 'Remote',
        requiredSkills: ['Shopify', 'SEO', 'Marketing'],
        experienceLevel: 'Junior',
        jobType: 'Full-time',
        track: 'E-commerce',
      },
      {
        title: 'Financial Analyst Intern',
        company: 'FinTech Solutions',
        location: 'New York, USA',
        requiredSkills: ['Excel', 'Finance', 'Analysis'],
        experienceLevel: 'Fresher',
        jobType: 'Internship',
        track: 'Finance',
      },
      {
        title: 'Penetration Tester',
        company: 'HackShield',
        location: 'Remote',
        requiredSkills: ['Pentesting', 'Linux', 'Security Tools'],
        experienceLevel: 'Junior',
        jobType: 'Full-time',
        track: 'Cybersecurity',
      },
      {
        title: 'IT Consultant',
        company: 'ConsultTech',
        location: 'London, UK',
        requiredSkills: ['IT Strategy', 'Client Communication'],
        experienceLevel: 'Mid',
        jobType: 'Full-time',
        track: 'Consulting',
      },
      {
        title: 'Cloud Security Engineer',
        company: 'SecureCloud',
        location: 'Remote',
        requiredSkills: ['AWS Security', 'IAM', 'Networking'],
        experienceLevel: 'Mid',
        jobType: 'Full-time',
        track: 'Cybersecurity',
      },
      {
        title: 'UI Designer',
        company: 'DesignSphere',
        location: 'New Delhi, India',
        requiredSkills: ['Figma', 'UI Design'],
        experienceLevel: 'Fresher',
        jobType: 'Internship',
        track: 'Design',
      },
      {
        title: 'Technical Writer',
        company: 'DocuHaus',
        location: 'Remote',
        requiredSkills: ['Documentation', 'Writing'],
        experienceLevel: 'Junior',
        jobType: 'Full-time',
        track: 'Content Creation',
      },
      {
        title: 'Operations Coordinator',
        company: 'OpsForce',
        location: 'Chicago, USA',
        requiredSkills: ['Coordination', 'Management'],
        experienceLevel: 'Junior',
        jobType: 'Full-time',
        track: 'Operations',
      },
      {
        title: 'Social Media Intern',
        company: 'BuzzOnline',
        location: 'Remote',
        requiredSkills: ['Social Media', 'Creativity'],
        experienceLevel: 'Fresher',
        jobType: 'Internship',
        track: 'Digital Marketing',
      },
      {
        title: 'Data Engineer',
        company: 'DataBridge',
        location: 'Remote',
        requiredSkills: ['Python', 'Spark', 'ETL'],
        experienceLevel: 'Mid',
        jobType: 'Full-time',
        track: 'Data Engineering',
      },
    
      // 20 MORE (to reach 100)
      {
        title: 'IT Intern',
        company: 'TechSupport Co.',
        location: 'Remote',
        requiredSkills: ['NetworkingBasics', 'Troubleshooting'],
        experienceLevel: 'Fresher',
        jobType: 'Internship',
        track: 'IT Support',
      },
      {
        title: 'Scrum Master',
        company: 'AgileFlow',
        location: 'Remote',
        requiredSkills: ['Scrum', 'Agile', 'Leadership'],
        experienceLevel: 'Mid',
        jobType: 'Full-time',
        track: 'Project Management',
      },
      {
        title: 'Game Artist',
        company: 'EpicArts',
        location: 'Remote',
        requiredSkills: ['Illustration', 'Character Design'],
        experienceLevel: 'Junior',
        jobType: 'Full-time',
        track: 'Game Development',
      },
      {
        title: 'Sound Designer',
        company: 'SoundWorks',
        location: 'Los Angeles, USA',
        requiredSkills: ['Sound Editing', 'DAWs'],
        experienceLevel: 'Junior',
        jobType: 'Part-time',
        track: 'Media Production',
      },
      {
        title: 'AI Consultant',
        company: 'AIPro Consulting',
        location: 'Remote',
        requiredSkills: ['AI Strategy', 'Python'],
        experienceLevel: 'Mid',
        jobType: 'Full-time',
        track: 'Artificial Intelligence',
      },
      {
        title: 'Web Designer',
        company: 'CreativeWebs',
        location: 'Remote',
        requiredSkills: ['Figma', 'HTML', 'CSS'],
        experienceLevel: 'Junior',
        jobType: 'Freelance',
        track: 'Design',
      },
      {
        title: 'CRM Specialist',
        company: 'ClientCare',
        location: 'Remote',
        requiredSkills: ['CRM Tools', 'Customer Support'],
        experienceLevel: 'Mid',
        jobType: 'Full-time',
        track: 'Sales',
      },
      {
        title: 'Ads Manager',
        company: 'AdBooster',
        location: 'Dubai, UAE',
        requiredSkills: ['Meta Ads', 'Google Ads'],
        experienceLevel: 'Junior',
        jobType: 'Full-time',
        track: 'Digital Marketing',
      },
      {
        title: 'Market Research Analyst',
        company: 'InsightHub',
        location: 'Remote',
        requiredSkills: ['Research', 'Analytics'],
        experienceLevel: 'Junior',
        jobType: 'Full-time',
        track: 'Marketing',
      },
      {
        title: 'Legal Assistant',
        company: 'LawGroup',
        location: 'New York, USA',
        requiredSkills: ['Documentation', 'Research'],
        experienceLevel: 'Fresher',
        jobType: 'Part-time',
        track: 'Legal',
      },
      {
        title: 'Cybersecurity Intern',
        company: 'SecuLabs',
        location: 'Remote',
        requiredSkills: ['Linux', 'Networking'],
        experienceLevel: 'Fresher',
        jobType: 'Internship',
        track: 'Cybersecurity',
      },
      {
        title: 'Backend Intern',
        company: 'DevHouse',
        location: 'Remote',
        requiredSkills: ['Node.js', 'MongoDB'],
        experienceLevel: 'Fresher',
        jobType: 'Internship',
        track: 'Backend Development',
      },
      {
        title: 'Full Stack Intern',
        company: 'BuildSoft',
        location: 'Remote',
        requiredSkills: ['React', 'Node.js'],
        experienceLevel: 'Fresher',
        jobType: 'Internship',
        track: 'Web Development',
      },
      {
        title: 'Cloud Intern',
        company: 'CloudWorks',
        location: 'Remote',
        requiredSkills: ['AWS Basics', 'Linux'],
        experienceLevel: 'Fresher',
        jobType: 'Internship',
        track: 'Cloud Computing',
      },
      {
        title: 'Marketing Intern',
        company: 'MarketMax',
        location: 'Remote',
        requiredSkills: ['Creativity', 'Marketing Basics'],
        experienceLevel: 'Fresher',
        jobType: 'Internship',
        track: 'Digital Marketing',
      },
      {
        title: 'Sales Intern',
        company: 'SalesCorp',
        location: 'Remote',
        requiredSkills: ['Communication'],
        experienceLevel: 'Fresher',
        jobType: 'Internship',
        track: 'Sales',
      },
      {
        title: 'Graphic Design Intern',
        company: 'DesignLab',
        location: 'Remote',
        requiredSkills: ['Illustrator', 'Figma'],
        experienceLevel: 'Fresher',
        jobType: 'Internship',
        track: 'Design',
      },
      {
        title: 'Data Entry Assistant',
        company: 'DataWorks',
        location: 'Remote',
        requiredSkills: ['Typing', 'Excel'],
        experienceLevel: 'Fresher',
        jobType: 'Part-time',
        track: 'Operations',
      },
      {
        title: 'HR Intern',
        company: 'HRConnect',
        location: 'Remote',
        requiredSkills: ['Recruitment Basics'],
        experienceLevel: 'Fresher',
        jobType: 'Internship',
        track: 'Human Resources',
      },
      {
        title: 'Virtual Assistant',
        company: 'VirtualTask',
        location: 'Remote',
        requiredSkills: ['Organization', 'Communication'],
        experienceLevel: 'Fresher',
        jobType: 'Freelance',
        track: 'Administration',
      }
    ];
    

    // Insert jobs
    await Job.insertMany(jobs);
    console.log(`✅ Successfully seeded ${jobs.length} jobs`);

    process.exit(0);
  } catch (error) {
    console.error('Error seeding jobs:', error);
    process.exit(1);
  }
};

// Run seed if called directly
if (require.main === module) {
  seedJobs();
}

module.exports = seedJobs;

